Testing 61 ckb next doesnt remember settings after restart
mattanger/ckb-next pull request #90
Opened 2017-02-26 17:25 UTC by frickler24

At the suggestion of @tatokis, not only the writability of the config file itself is evaluated,
but also reasons why the file could not be created.

This means that the original functions of QSettings are not enough, but we want to save the system independency given by QSettings.

So first try is to create a test entry in the Config.
If this test entry can be read after closing and reopening the config file, the file is writable or can be created. 

This PR fixes issue #61 and replaces PR #71  which was based on master. This one is based on testing.

2017-03-03 21:45 UTC, light2yellow commented
How can I test it?

2017-03-03 22:08 UTC, frickler24 commented
@light2yellow make a chmod 0 to ~/.config/.ckb-next
or make a chmod 400 or similar to ~/.config/.ckb-next/ckb-next.conf
or do something else with your Profile so that it is not writable
Then start ckb and a panel must appear with the warning.

If conf file is writable, nothing new happens.

2017-03-04 01:48 UTC, light2yellow commented
I see the message but there are few issues I would like to point out:
* The spacing between the upper and the lower borders is... too big?
* I had to close a window asking me to choose my layout first (that window that everyone see when launching for the first time). I think it should be displayed after presing OK on the window generated by this patch

2017-03-04 01:58 UTC, ghost requested changes

2017-03-04 01:58 UTC, light2yellow commented on src/ckb/ckbsettings.cpp
> +    QString info = "This might happen, if you started the ckb-next program with root privileges earlier.\nOr did you copy it from somewhere?\n\nPlease have a look at "
> This might happen, if

Comma not needed.

2017-03-04 02:00 UTC, light2yellow commented on src/ckb/ckbsettings.cpp
> +    QString info = "This might happen, if you started the ckb-next program with root privileges earlier.\nOr did you copy it from somewhere?\n\nPlease have a look at "
(I'm also trying out "review" features :) )

2017-03-05 10:29 UTC, frickler24 commented on src/ckb/ckbsettings.cpp
> +    QString info = "This might happen, if you started the ckb-next program with root privileges earlier.\nOr did you copy it from somewhere?\n\nPlease have a look at "
good function!
Now I can see my correction commit, but it is in the "normal" flow.
How can I mark  9556c84 as corresponding to your specific review?

2017-03-05 10:56 UTC, frickler24 commented
@light2yellow I reduced the spacing a bit and moved the filename into a new line.
More complex would be to synchronize the two panels, because they come from different threads and the creation of the thread is done before checking the config file.
The only chance would be with a separate semaphore.
Or is there a way to check in Qt for existence of a somehow statically named window?

2017-03-05 12:18 UTC, light2yellow commented
> ...if you did start the ckb-next program with root privileges earlier...

According to [ckb/main.cpp#L165](https://github.com/mattanger/ckb-next/blob/testing/src/ckb/main.cpp#L165) the app won't allow a user to be run as root under any circumstances. So I think this is redundant. I guess a message like 

> Your profile information for ckb-next is non-writable `note: "not writable" -> "non-writable"`. Please check the file system permissions of %ckb_dirname%.

should suffice.

We should also log it with `ckb_err()`.

> The only chance would be with a separate semaphore.

Isn't it possible to merge them together? I mean adding this functionality into the method that checks whether the config exists (just that), then if it does, check for being writable.

2017-03-05 12:18 UTC, ghost approved these changes

2017-03-05 12:18 UTC, light2yellow commented on src/ckb/ckbsettings.cpp
> +            /// So we need to add the original isWritabel() function.
isWritabel() <- typo

2017-03-05 15:00 UTC, light2yellow commented on src/ckb/ckbsettings.cpp
> +    QString info = "This might happen, if you started the ckb-next program with root privileges earlier.\nOr did you copy it from somewhere?\n\nPlease have a look at "
I have no idea ¯\_(ツ)_/¯

2017-03-05 16:56 UTC, frickler24 commented
@light2yellow Sorry, I had a little trouble pushing my last commit. If there is a problem with the last commit  	dc02a24, I'll try to create a clean one again.

2017-03-11 13:01 UTC, light2yellow commented
Can someone else test this so it can be merged?

2017-03-11 22:21 UTC, light2yellow commented
Oh, I actually missed the new commits, sorry. I will re-test it tomorrow.

2017-04-25 12:25 UTC, tatokis commented
I just had some time to try this.
It still doesn't detect if the directory is owned by root.

Additionally, I think we should quit after the user has seen the warning, instead of normally resuming operation, in order to avoid any possible profile overwriting.

2017-05-05 20:43 UTC, fleischie commented
Hey, I have a mac now (thank you employer 😀 ). Is there anything mac-related I should test? Respectively: What's the status on this?

2017-05-06 22:55 UTC, frickler24 commented
@tatokis Now I added an explicit separate file for checking your condition mentioned.
Did you delete your config file when you chown-ed the directory to root? Otherwise there is a file which you own in a directory which is not writable - but the file is writable. 
Both cases were detected correctly on my system. Nevertheless, now a writable file in a non writable directory is detected and mentioned.
As you wanted, the client stops now after the message disappeared.
@fleischie Please test it with your new mac (congratulation for your employer :-) 
Find any situation where you cannot access your config file:
File is r/o, you do not own the file, you do not own the directory with the file and have no permission to write to the dir etc.
After all tests there should be no new additional file in the directory where your configs are stored.

2017-05-07 16:40 UTC, fleischie commented
Hey, I have done some testing on Mac OS (El Capitan 10.11.6). First of all, it took me like 2 hours to find the settings file. 😅

Nevertheless I conducted the following test cases with the following results:

# Tests

## Settings file does not exist (prior to test)

### Directory permission permutations

| dir readable | dir writeable | dir executable | result |
| --- | --- | --- | --- |
| true | true | true | default behavior |
| true | true | false | open dialog |
| true | false | true | open dialog |
| true | false | false | open dialog |
| false | true | true | default behavior |
| false | true | false | open dialog |
| false | false | true | open dialog |
| false | false | false | open dialog |

Conclusion: If directory is writeable and executable the default behavior is triggered, in any other case the dialog box is opened. Strangely `ckb` is not asking for the keyboard layout.

## Settings file exists

### File permission permutations

Prerequisite: Directory is 700 with karl:staff ownership.

| file readable | file writeable | result |
| --- | --- | --- |
| true | true | default behavior |
| true | false | default behavior |
| false | true | initial start |
| false | false | initial start |

Conclusion: File readability determines, whether the default or the initial behavior is triggered.

### Dir permission permutations

Prerequisite: File mode is 400 and has karl:staff ownership.

| dir readable | dir writeable | dir executable | result |
| --- | --- | --- | --- |
| true | true | true | default behavior |
| true | true | false | open dialog |
| true | false | true | open dialog |
| true | false | false | open dialog |
| false | true | true | default behavior |
| false | true | false | open dialog |
| false | false | true | open dialog |
| false | false | false | open dialog |

Conclusion: If directory is writeable and executable the default behavior is triggered, in any other case the dialog box is opened.

----

I did some more permutations with file/dir permissions + ownerships but it boils down to the above-mentioned tables.

Additionally I don't think the operating system flavor (mac vs. linux) has an effect on this table, as the rwx-permissions are pretty much the same and it's all in user-spaced territory (the settings file is not stored on global directories).

P.S.: I might have over-engineered the tests for such a simple PR. 😄

2017-05-07 21:43 UTC, frickler24 commented
@fleischie Wow, thanks a lot!
To 1.: 
> Strangely ckb is not asking for the keyboard layout.

This is correct, Tatokis tip was to terminate the session if config file is nonwritable.
To 2.:
> true 	false 	default behavior: 

This should not happen. On my linux I get the open dialog.
Please have a look at ckbsettings.cpp: static QSettings* globalSettings(){ (beginning from line 27).
At least the function testSettings->isWritable() in line 64 should give false as retval.
Your third matrix show the same effect. The dependency should both be from write-access and read-acces.
perm==0--> Warning-panel
perm==400--> Warning-panel
perm==200--> currently I did not check this one. Behavior at linux is Warning-panel because of testSettings->isWritable()==false.
perm==600--> default

My thought was to use the machine independent function as far as possible.
If we get problems with it, I change it and have a look at fstat at the dir and file.

2017-09-05 03:31 UTC, closed without merging